# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alun You's Blog
email: higherone@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blogging can be joyful.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://alunyou.github.io" # the base hostname & protocol for your site
linkedin_username: alunyou
github_username:  AlunYou

# Build settings
markdown: kramdown
